spring:
  cloud:
    gateway:
      routes:
        - id: purchase-service
          uri: http://localhost:9092
          predicates:
            - Path=/api/purchase/**
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/**
